Add auto fix functionality
Stuk/eslint-plugin-header pull request #12
Opened 2017-08-30 21:57 UTC by pranaygp

Closes #10 

This is a feature we need for a project that we're soon launching to ensure that all our code has the appropriate copyright header line.

2017-09-12 02:25 UTC, Stuk requested changes
Thank you so much for the contribution! This is great!

I have a few comments in review.

`npm test` and `npm run lint` seem to be failing. Could you look at those and make the needed changes?

Also, I appreciate that yarn is fast and cool but I'm not using it on this project, so could you remove the yarn.lock file?

2017-09-12 02:25 UTC, Stuk commented on lib/rules/header.js
> +function genPrependFixer(commentType, context, node, headerLines) {
`context` isn't used here. Could you remove it?

2017-09-12 02:25 UTC, Stuk commented on lib/rules/header.js
> +    var shouldFix = false;
Would this be better named `canFix`?

Either way, could you add a brief comment explaining that this is false if any lines are regexes?

2017-09-12 02:25 UTC, Stuk commented on lib/rules/header.js
> +                            },
This data isn't used in this message

2017-09-12 02:25 UTC, Stuk commented on lib/rules/header.js
> +                                },
This data isn't used in this message

2017-09-12 02:25 UTC, Stuk commented on lib/rules/header.js
> +                            },
This data isn't used in this message

2017-09-12 18:57 UTC, pranaygp commented
Gotcha!

I'm a little surprised `npm test` didn't pass. seems to work locally. Could you give that a shot again? 

Also, I'm adding `yarn.lock` to the .gitignore to make that explicit

2017-09-12 19:45 UTC, pranaygp commented
I opened up #13 to address lint issues since they weren't from the code changes in this PR. It's branched off this to ensure easy merging after this PR is merged :D

2017-09-13 03:37 UTC, Stuk approved these changes

2017-09-13 03:39 UTC, merged

2017-09-13 03:40 UTC, Stuk commented
Thank you for the code! Something was wrong with my local Node install, tests are all passing now (confirmed by Travis!)

2017-09-13 03:42 UTC, Stuk commented
Published as v1.2.0